import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FooterStatus from '@/components/FooterStatus'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-white dark:bg-neutral-950 text-neutral-900 dark:text-neutral-100`}>
        <header className="h-12 border-b border-gray-200 dark:border-neutral-800 flex items-center px-4 text-sm font-medium">
          AIX Chat
        </header>
        <main className="min-h-[calc(100vh-96px)]">{children}</main>
        <footer className="h-12 border-t border-gray-200 dark:border-neutral-800 flex items-center justify-between px-4 text-xs text-neutral-500">
          <span>Built with Next.js 15 + Vercel AI SDK</span>
          {/* Token counter client component */}
          <FooterStatus />
        </footer>
      </body>
    </html>
  );
}
